name: Update stats

on:
  schedule: # execute every 4 days
    - cron: "0 0 */7 * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: /
        env:
          GITHUB_TOKEN: ${{ secrets.STATS_TOKEN }}
